apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: corpora
  namespace: corpora
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /corpora
          backend:
            serviceName: corpora
            servicePort: 80
